version: "3.8"
services:
  easyocr-api:
    build: .
    runtime: nvidia
    ports:
      - 7757:7757
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
